language: cpp
os: windows
arch: amd64
compiler: clang

before_install:
- choco install hg
script:
- clang --version
- C:\\Program\ Files\\Mercurial\\hg.exe
- "C:\\Program\ Files\\Mercurial\\hg.exe"
- "C:/Program\ Files/Mercurial/hg.exe"
- "/C/Program\ Files/Mercurial/hg.exe"
- /C/Program\ Files/Mercurial/hg.exe
- echo $PATH

  
  
