language: cpp
os: windows
arch: amd64

before_install:
- choco install hg
- export PATH=$PATH:/C/Program\ Files/Mercurial

script:
- clang --version
- echo C:\\Program\ Files\\Mercurial\\hg.exe   # Ok
- echo /C/Program\ Files/Mercurial/hg.exe      # Ok
- echo C:/Program\ Files/Mercurial/hg.exe      # Ok, recommended
- echo '/C/Program\ Files/Mercurial/hg.exe'    # Ok
- echo 'C:/Program\ Files/Mercurial/hg.exe'    # Ok
- echo "C:\\Program\ Files\\Mercurial\\hg.exe" # Fail, double-qute will escape <backslash><space> too early!
- echo "C:/Program\ Files/Mercurial/hg.exe"    # Fail
- echo "/C/Program\ Files/Mercurial/hg.exe"    # Fail

- echo $PATH
- echo $SHELL
- python --version

- git clone --branch master https://github.com/imharrywu/mozillabuildsetup /c/mozilla-build
- export PATH=/c/Users/travis/.cargo/bin:/local/bin:/c/mozilla-build/bin:/c/mozilla-build/kdiff3:/c/mozilla-build/nsis-3.01:/c/mozilla-build/python:/c/mozilla-build/python/Scripts:/c/mozilla-build/python3:/c/mozilla-build/python3/Scripts:.:/usr/local/bin:/mingw/bin:/bin:$PATH
- git clone --branch master https://github.com/imharrywu/mozilla-central /c/mozilla-central #hg clone -b default https://hg.mozilla.org/mozilla-central/ /c/mozilla-central
- cd /c/mozilla-central
- pwd
- export MOZ_WINDOWS_BOOTSTRAP=1
- ./mach busted
- ./mach bootstrap --no-interactive --application-choice browser
- ./mach busted


  
  
