language: cpp
os: windows
arch: amd64
compiler: clang
cache:
  directories:
  - /c/mozilla-build
  - /c/mozilla-central
  - /c/mozilla-central
  
before_install:
- choco install hg
script:
- clang --version
- echo C:\\Program\ Files\\Mercurial\\hg.exe   # Ok
- echo /C/Program\ Files/Mercurial/hg.exe      # Ok
- C:/Program\ Files/Mercurial/hg.exe      # Ok, recommended
- echo '/C/Program\ Files/Mercurial/hg.exe'    # Ok
- echo 'C:/Program\ Files/Mercurial/hg.exe'    # Ok
- echo "C:\\Program\ Files\\Mercurial\\hg.exe" # Fail, double-qute will escape <backslash><space> too early!
- echo "C:/Program\ Files/Mercurial/hg.exe"    # Fail
- echo "/C/Program\ Files/Mercurial/hg.exe"    # Fail
- export PATH=$PATH:/C/Program\ Files/Mercurial
- hg
- echo $PATH
- test ! -d /c/mozilla-build && git clone --branch master https://github.com/imharrywu/mozillabuildsetup /c/mozilla-build
- test ! -d /c/mozilla-central && git clone --branch master https://github.com/imharrywu/mozilla-central /c/mozilla-central #hg clone -b default https://hg.mozilla.org/mozilla-central/ /c/mozilla-central
- cd /c/mozilla-central
- /c/mozilla-build/start-shell.bat \"/c/mozilla-central/mach\ bootstrap\ --no-interactive\ --application-choice\ browser\"
- /c/mozilla-build/start-shell.bat \"/c/mozilla-central/mach\ build\"


  
  
