language: cpp
os: windows
arch: amd64
compiler: clang

before_install:
- choco install hg
script:
- clang --version
- git clone https://github.com/imharrywu/mozillabuildsetup C:/mozilla-build
- echo $PATH

  
  
