language: cpp
os: windows
arch: amd64
compiler: clang

before_install:
- choco install hg
script:
- clang --version
- C:\\Program\ Files\\Mercurial\\hg.exe   # Ok
- /C/Program\ Files/Mercurial/hg.exe      # Ok
- C:/Program\ Files/Mercurial/hg.exe      # Ok
- "C:\\Program\ Files\\Mercurial\\hg.exe" # Fail
- "C:/Program\ Files/Mercurial/hg.exe"    # Fail
- 'C:/Program\ Files/Mercurial/hg.exe'    # Fail
- "/C/Program\ Files/Mercurial/hg.exe"    # Fail
- '/C/Program\ Files/Mercurial/hg.exe'    # Fail

- echo $PATH

  
  
