language: cpp
os: windows
arch: amd64
compiler: clang

before_install:
  - choco install hg
  - refreshenv.cmd
script:
  - clang --version
  - git clone https://github.com/imharrywu/mozillabuildsetup C:/mozilla-build
  - hg clone https://hg.mozilla.org/mozilla-central c:/mozilla-central
  - c:/mozilla-build/start-shell.bat "/c/mozilla-central/mach build"
  
  
