language: cpp
os: windows
arch: amd64
compiler: clang
cache:
  directories:
  - /c/mozilla-build
before_install:
  - choco install hg
script:
  - clang --version
  - test ! -d /c/mozilla-build && git clone https://github.com/imharrywu/mozillabuildsetup /c/mozilla-build
  - hg clone https://hg.mozilla.org/mozilla-central
  
